In [1]:
import tensorflow as tf
import numpy as np

In [18]:
shape=(2,3)
shape_sum=sum(shape)
print shape_sum

epsilon=np.sqrt(6.0/shape_sum)
print epsilon

#print [sum(shape[i]) for i in range(len(shape))]
    #sum_=sum_+shape[i]

#print sum_
#eclipson=np.sqrt(6/)

5
1.0954451150103321


In [19]:
tf.random_uniform(shape,maxval=epsilon,minval=-epsilon)

<tf.Tensor 'random_uniform:0' shape=(2, 3) dtype=float32>

In [4]:
b=list()
b.append((a[-2],a[-1]))

In [8]:
del a[-2]

In [9]:
a

[1, 3]

In [14]:
a=[6,7,8,9,10,11]
batch_size=3

In [15]:
for i in range(0,len(a),batch_size):
    print a[i:i+batch_size]

[6, 7, 8]
[9, 10, 11]


In [13]:
a[10:14]

[11]

In [24]:
#Question 1 a
x=tf.constant(np.array([[-1001, -1002]]), dtype=tf.float32)

with tf.Session() as sess:
    #find max element in each row
    max_x=tf.reduce_max(x,axis=1,keep_dims=True)
    
    #substract max element from each row
    diff_x=tf.subtract(x,max_x)
    
    #take exp of each elemet
    exp_x=tf.exp(diff_x)
    
    #sum each row 
    sum_x=tf.reduce_sum(exp_x,axis=1,keep_dims=True)
    
    #calculate softmaxt
    out=tf.divide(exp_x,sum_x)
    
    print sess.run(out)

[[0.7310586  0.26894143]]


In [42]:
#Question 1 b
y = np.array([[0, 1], [1, 0], [1, 0]])
yhat = np.array([[.5, .5], [.5, .5], [.5, .5]])
tf.constant(y, dtype=tf.int32), tf.constant(yhat, dtype=tf.float32)

with tf.Session() as sess:
    #log of yhat
    yhat_log=tf.log(yhat)
    
    #multiply y and y_hat element wise
    out=tf.multiply(tf.to_float(y),tf.to_float(yhat_log))
    
    #row wise sum
    out=tf.reduce_sum(out,axis=1,keepdims=True)
    
    #sum for minibatch
    out=-tf.reduce_sum(out)
    
    print sess.run(out)

2.0794415


1.3862944


In [9]:
x=tf.constant([[1,2,3,4],[5,6,7,8]],dtype=tf.float16)

In [10]:
sess=tf.Session()
sess.run(tf.exp(x))

array([[2.719e+00, 7.391e+00, 2.008e+01, 5.459e+01],
       [1.484e+02, 4.035e+02, 1.097e+03, 2.980e+03]], dtype=float16)

In [24]:
max_=sess.run(tf.reduce_max(x,axis=1))
max_

array([4., 8.], dtype=float16)

In [26]:
sess.run(tf.subtract(x,max_))

ValueError: Dimensions must be equal, but are 4 and 2 for 'Sub_3' (op: 'Sub') with input shapes: [2,4], [2].

In [28]:
sess.run(tf.expand_dims(max_,1))

array([[4.],
       [8.]], dtype=float16)

In [21]:
sess.run(tf.subtract(x,1))

array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]], dtype=float16)

In [31]:
sess.run(tf.shape(x)),sess.run(tf.shape(tf.expand_dims(max_,1)))

(array([2, 4], dtype=int32), array([2, 1], dtype=int32))

In [37]:
sum_exp=sess.run(tf.expand_dims(tf.reduce_sum(tf.exp(tf.subtract(x,tf.expand_dims(max_,1))),axis=1),1))
sum_exp

array([[1.553],
       [1.553]], dtype=float16)

In [38]:
exp=sess.run(tf.exp(tf.subtract(x,tf.expand_dims(max_,1))))
    exp

array([[0.04977, 0.1354 , 0.368  , 1.     ],
       [0.04977, 0.1354 , 0.368  , 1.     ]], dtype=float16)

In [42]:
sess.run(tf.divide(tf.constant(exp),tf.constant(sum_exp)))

array([[0.03204, 0.08716, 0.2369 , 0.644  ],
       [0.03204, 0.08716, 0.2369 , 0.644  ]], dtype=float16)

In [44]:
sess.run(tf.divide(tf.exp(tf.subtract(x,tf.expand_dims(max_,1))),tf.expand_dims(tf.reduce_sum(tf.exp(tf.subtract(x,tf.expand_dims(max_,1))),axis=1),1)))

array([[0.03204, 0.08716, 0.2369 , 0.644  ],
       [0.03204, 0.08716, 0.2369 , 0.644  ]], dtype=float16)

In [41]:
type(max_)

numpy.ndarray

In [45]:
x_max = tf.reduce_max(x,1,keep_dims=True)          # find row-wise maximums
x_sub = tf.subtract(x,x_max)                       # subtract maximums
x_exp = tf.exp(x_sub)                              # exponentiation
sum_exp = tf.reduce_sum(x_exp,1,keep_dims=True)    # row-wise sums
out = tf.div(x_exp,sum_exp) 

Instructions for updating:
keep_dims is deprecated, use keepdims instead
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.


In [48]:
sess.run(out)

array([[0.03204, 0.08716, 0.2369 , 0.644  ],
       [0.03204, 0.08716, 0.2369 , 0.644  ]], dtype=float16)

In [52]:
x=tf.to_float(tf.constant([[0,1],[1,0],[1,0]],dtype=tf.int32))
y=tf.constant([[0.5,0.5],[0.5,0.5],[0.5,0.5]],dtype=tf.float32)

Instructions for updating:
Use tf.cast instead.


In [53]:
mul=tf.multiply(x,y)

In [54]:
cel=tf.reduce_sum(mul)

In [55]:
sess.run(cel)

1.5