In [1]:
import numpy as np

In [10]:
quad = lambda x: (np.sum(x ** 2), x * 2)

quad(np.array([2,3]))[1]

array([4, 6])

In [7]:
a=np.array([[1001,1002,1003],[3,4,5]])
a

array([[1001, 1002, 1003],
       [   3,    4,    5]])

In [14]:
x[[0,1]]=a
x

array([[1001., 1002., 1003.],
       [   3.,    4.,    5.],
       [   0.,    0.,    0.],
       [   0.,    0.,    0.]])

In [67]:
temp=a-np.reshape(max_,(a.shape[0],1))
temp

array([[-2, -1,  0],
       [-2, -1,  0]])

In [68]:
exp_temp=np.exp(temp)
exp_temp

array([[0.13533528, 0.36787944, 1.        ],
       [0.13533528, 0.36787944, 1.        ]])

In [69]:
exp_temp/(np.sum(exp_temp,axis=1).reshape(a.shape[0],1).astype(float))

array([[0.09003057, 0.24472847, 0.66524096],
       [0.09003057, 0.24472847, 0.66524096]])

In [22]:
np.reshape(max_,(2,1))

array([[2],
       [4]])

In [62]:
a.shape[0],1

(2, 1)

In [45]:
a

array([[1, 2],
       [2, 4]])

In [1]:
import numpy as np

In [2]:
N = 20
dimensions = [10, 5, 10]
data = np.random.randn(N, dimensions[0])   # each row will be a datum
labels = np.zeros((N, dimensions[2]))
for i in xrange(N):
    labels[i, np.random.randint(0,dimensions[2]-1)] = 1

params = np.random.randn((dimensions[0] + 1) * dimensions[1] + (dimensions[1] + 1) * dimensions[2], )


In [6]:
(dimensions[0] + 1) * dimensions[1] + (dimensions[1] + 1) * dimensions[2],

(115,)

In [14]:
a=np.array([1,2,3])
b=np.array([4,5])
a

array([1, 2, 3])

In [17]:
np.outer(a,b)

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [1]:
import numpy as np

In [51]:
x=np.array([[1,2],[3,4],[5,6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
np.apply_along_axis(lambda x : x/np.sqrt(x.dot(x)),1,x)

array([[0.4472136 , 0.89442719],
       [0.6       , 0.8       ]])

In [31]:
import random
def dummySampleTokenIdx():
        return random.randint(0, 4)

def getRandomContext(C):
    tokens = ["a", "b", "c", "d", "e"]
    return tokens[random.randint(0,4)],[tokens[random.randint(0,4)] for i in range(2*C)]

In [33]:
getRandomContext(2)

('c', ['b', 'e', 'e', 'e'])

In [53]:
x


array([[1, 2],
       [3, 4],
       [5, 6]])

In [64]:
y=np.array([1,2,3])
y.shape

(3,)

In [48]:
np.sum(np.exp(np.dot(x,y)))

60022.5548743004

In [57]:
np.exp(np.dot(x,y)).reshape(3,1)*x

array([[1.48413159e+02, 2.96826318e+02],
       [1.79622425e+05, 2.39496567e+05],
       [1.20774764e+08, 1.44929717e+08]])

In [66]:
x,y

(array([[1, 2],
        [3, 4],
        [5, 6]]), array([1, 2, 3]))

In [76]:
np.sum(x*y.reshape(3,1),axis=0)/2+np.array([1,2])

array([12, 16])

In [63]:
y.shape

(2,)

In [7]:
gradIn = np.ones([3,2])/2
gradIn

array([[0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5]])

In [1]:
import numpy as np

In [10]:
x=np.array([[1,2]])
x

array([[1, 2]])

In [12]:
np.repeat(x,2,axis=0)

array([[1, 2],
       [1, 2]])

In [16]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,2],[6,4]])

In [17]:
np.add(x,y)

array([[6, 4],
       [9, 8]])