In [57]:
data=[([[1,9], [2,9], [3,8], [4,8]], [1, 1, 4, 4])]
start=[5,8] 
end=[6,8]
window_size=1

In [72]:
form_data = [[start]*window_size+i[0]+[end]*window_size for i in data]
form_data

[[[5, 8], [1, 9], [2, 9], [3, 8], [4, 8], [6, 8]]]

In [93]:
final_result=[]
data=[([[1,9], [2,9], [3,8], [4,8]], [1, 1, 4, 4])]
form_data = [[start]*window_size+i[0]+[end]*window_size for i in data]
#print form_data

for sen,lab in enumerate(data):
    for index in range(window_size,window_size+len(data[0][1])):
        print index
        temp=([j for i in form_data[ind][index-1:index+window_size+1] for j in i],data[ind][1][index-window_size])
        print temp
    
        final_result.append(temp)
    
print final_result

1
([5, 8, 1, 9, 2, 9], 1)
2
([1, 9, 2, 9, 3, 8], 1)
3
([2, 9, 3, 8, 4, 8], 4)
4
([3, 8, 4, 8, 6, 8], 4)
[([5, 8, 1, 9, 2, 9], 1), ([1, 9, 2, 9, 3, 8], 1), ([2, 9, 3, 8, 4, 8], 4), ([3, 8, 4, 8, 6, 8], 4)]


In [90]:
for sen,lab in [([[1,9], [2,9], [3,8], [4,8]], [1, 1, 4, 4])]:
    print sen
    print lab

[[1, 9], [2, 9], [3, 8], [4, 8]]
[1, 1, 4, 4]


In [53]:
window_size=2
range(window_size,window_size+len(data[0][1]))

[2, 3, 4, 5]

In [46]:
a[i-1:i+2]

[2, 3, 4]

In [95]:
data=[([[1,9], [2,9], [3,8], [4,8]], [1, 1, 4, 4])]
form_data = [[start]*window_size+i[0]+[end]*window_size for i in data]
form_data

[[[5, 8], [1, 9], [2, 9], [3, 8], [4, 8], [6, 8]]]

In [110]:
window_size=1
windowed_data=[]
for sentence, label in data:
    print sentence,label
    sentence=[start]*window_size+sentence+[end]*window_size
    
    for index in range(window_size,window_size+len(label)):
        windowed_data.append( ([j for i in sentence[index-window_size:index+window_size+1] for j in i]\
                               ,label[index-window_size]))
print windowed_data

[[1, 9], [2, 9], [3, 8], [4, 8]] [1, 1, 4, 4]
[([5, 8, 1, 9, 2, 9], 1), ([1, 9, 2, 9, 3, 8], 1), ([2, 9, 3, 8, 4, 8], 4), ([3, 8, 4, 8, 6, 8], 4)]


In [1]:
import tensorflow as tf

In [24]:
sess = tf.Session()
a=tf.constant([[1,2],[3,4],[5,6]])
b=tf.constant([[1,2,3],[4,5,6]])

b1=tf.constant([1,2,3])
print sess.run(tf.matmul(a,b))
print sess.run(tf.matmul(a,b)+b1)

# [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]



[[ 9 12 15]
 [19 26 33]
 [29 40 51]]
[[10 14 18]
 [20 28 36]
 [30 42 54]]


In [15]:
@ dec
def func():
    print "I am ordinary"
    

I am decorated
I am ordinary


In [8]:
def dec(func):
    print "I am decorated"
    func()
    return dec

In [13]:
pretty=dec(func)

I am decorated
I am ordinary


function

In [21]:
@ dec
def divide(a,b):
    return a/b

I am decorated


TypeError: divide() takes exactly 2 arguments (0 given)

In [19]:
def dec(divide):
    if b==0:
        print "divide by zero"
    divide(a,b)

ZeroDivisionError: integer division or modulo by zero

In [1]:
data=[([2650, 2649, 92, 2647, 1206, 2649], 1), ([92, 2647, 1206, 2649, 123, 2648], 4), ([1206, 2649, 123, 2648, 291, 2649], 3), ([123, 2648, 291, 2649, 7, 2649], 4), ([291, 2649, 7, 2649, 1941, 2649], 4), ([7, 2649, 1941, 2649, 81, 2648], 4), ([1941, 2649, 81, 2648, 546, 2649], 3), ([81, 2648, 546, 2649, 1, 2646], 4), ([546, 2649, 1, 2646, 2651, 2649], 4), ([2650, 2649, 2591, 2648, 206, 2648], 0)]

In [18]:
zip(*data)

[([2650, 2649, 92, 2647, 1206, 2649],
  [92, 2647, 1206, 2649, 123, 2648],
  [1206, 2649, 123, 2648, 291, 2649],
  [123, 2648, 291, 2649, 7, 2649],
  [291, 2649, 7, 2649, 1941, 2649],
  [7, 2649, 1941, 2649, 81, 2648],
  [1941, 2649, 81, 2648, 546, 2649],
  [81, 2648, 546, 2649, 1, 2646],
  [546, 2649, 1, 2646, 2651, 2649],
  [2650, 2649, 2591, 2648, 206, 2648]),
 (1, 4, 3, 4, 4, 4, 3, 4, 4, 0)]

In [13]:
import numpy as np
batches = [np.array(col) for col in zip(*data)]
batches

[array([[2650, 2649,   92, 2647, 1206, 2649],
        [  92, 2647, 1206, 2649,  123, 2648],
        [1206, 2649,  123, 2648,  291, 2649],
        [ 123, 2648,  291, 2649,    7, 2649],
        [ 291, 2649,    7, 2649, 1941, 2649],
        [   7, 2649, 1941, 2649,   81, 2648],
        [1941, 2649,   81, 2648,  546, 2649],
        [  81, 2648,  546, 2649,    1, 2646],
        [ 546, 2649,    1, 2646, 2651, 2649],
        [2650, 2649, 2591, 2648,  206, 2648]]),
 array([1, 4, 3, 4, 4, 4, 3, 4, 4, 0])]

In [24]:
data=batches
list_data=type(data) is list and (type(data[0]) is list or type(data[0]) is np.ndarray)
data_size=len(data[0]) if list_data else len(data)
indices = np.arange(data_size)
print indices

[0 1 2 3 4 5 6 7 8 9]


In [28]:
minibatch_start=np.arange(0, data_size, 2)[0]
indices[minibatch_start:minibatch_start + 2]

array([0, 1])

In [31]:
type(data[0])

numpy.ndarray

In [32]:
data[0][indices[minibatch_start:minibatch_start + 2]]

array([[2650, 2649,   92, 2647, 1206, 2649],
       [  92, 2647, 1206, 2649,  123, 2648]])

In [28]:
import numpy as np
def test():
    for i in np.arange(0, 10, 2):
       yield i

In [29]:
x=test()

0

In [12]:
import tensorflow as tf
labels=tf.constant(1., shape=(2,))
logits=tf.constant(1., shape=(50,2))
    labels = labels + tf.zeros_like(logits)


In [8]:
tf.Session().run(tf.nn.softmax_cross_entropy_with_logits(labels=labels, logits=logits))

array([1.3862944, 1.3862944, 1.3862944, 1.3862944, 1.3862944, 1.3862944,
       1.3862944, 1.3862944, 1.3862944, 1.3862944, 1.3862944, 1.3862944,
       1.3862944, 1.3862944, 1.3862944, 1.3862944, 1.3862944, 1.3862944,
       1.3862944, 1.3862944, 1.3862944, 1.3862944, 1.3862944, 1.3862944,
       1.3862944, 1.3862944, 1.3862944, 1.3862944, 1.3862944, 1.3862944,
       1.3862944, 1.3862944, 1.3862944, 1.3862944, 1.3862944, 1.3862944,
       1.3862944, 1.3862944, 1.3862944, 1.3862944, 1.3862944, 1.3862944,
       1.3862944, 1.3862944, 1.3862944, 1.3862944, 1.3862944, 1.3862944,
       1.3862944, 1.3862944], dtype=float32)

In [13]:
tf.Session().run(labels)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)