In [1]:
import numpy as np

In [7]:
x = np.array([[1, 2], [-1, -2]])
x*(x)

array([[1, 4],
       [1, 4]])

In [20]:
1.0/(1+np.exp(np.negative(x)))

array([[0.73105858, 0.88079708],
       [0.26894142, 0.11920292]])

In [21]:
def sigmoid(x):
    return 1.0/(1+np.exp(np.negative(x)))

In [27]:
x = np.array([[1, 2], [-1, -2]])
print sigmoid(x)

[[0.73105858 0.88079708]
 [0.26894142 0.11920292]]


In [30]:
def grad_sigmoid(x):
    return sigmoid(x)*(1-sigmoid(x))

In [31]:
print grad_sigmoid(x)

[[0.19661193 0.10499359]
 [0.19661193 0.10499359]]


In [1]:
x

NameError: name 'x' is not defined

In [8]:
quad = lambda x: (np.sum(x ** 2), x * 2)

In [27]:
quad(np.array([[1,2],[3,4]]))

(30, array([[2, 4],
        [6, 8]]))

In [11]:
quad, np.array(123.456)

(<function __main__.<lambda>>, array(123.456))

In [12]:
np.random.randn(3,)

array([1.47201424, 0.01978846, 1.91125663])

In [19]:
quad(np.random.randn(4,5))

(13.790948638422629,
 array([[ 2.32313314,  2.56352655,  0.7921342 ,  0.09530195,  0.80321365],
        [-0.86516876, -2.18803863,  0.49340424, -1.52768881, -0.84615123],
        [ 0.32686784, -3.78411154, -3.44166525,  0.64952178, -1.28018634],
        [ 0.58099184, -0.65710155,  0.82912415, -0.83644085, -1.61109045]]))

In [20]:
it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])

In [23]:
x=np.array([1,2])

In [25]:
while not it.finished:
    print it.multi_index
    it.iternext()

(0, 0)
(0, 1)
(1, 0)
(1, 1)


In [3]:
N = 20
dimensions = [10, 5, 10]
    

In [8]:
data = np.random.randn(N, dimensions[0])
labels = np.zeros((N, dimensions[2]))

In [9]:
labels.shape

(20, 10)

In [11]:
for i in xrange(N):
    labels[i, np.random.randint(0,dimensions[2]-1)] = 1

In [13]:
params = np.random.randn((dimensions[0] + 1) * dimensions[1] + (
        dimensions[1] + 1) * dimensions[2], )


In [18]:
ofs = 0
Dx, H, Dy = (dimensions[0], dimensions[1], dimensions[2])

W1 = np.reshape(params[ofs:ofs+ Dx * H], (Dx, H))
ofs += Dx * H
b1 = np.reshape(params[ofs:ofs + H], (1, H))
ofs += H
W2 = np.reshape(params[ofs:ofs + H * Dy], (H, Dy))
ofs += H * Dy
b2 = np.reshape(params[ofs:ofs + Dy], (1, Dy))


In [22]:
b2.shape

(1, 10)

In [28]:
a=np.array([[1,2],[2,3]])
b=np.array([[1,0],[0,1]])
a

array([[1, 2],
       [2, 3]])

In [31]:
np.sum(b*np.log(a))

1.0986122886681098